import 'food.dart';

/// Bundled food database.
///
/// Macros are per the stated serving and rounded from public composition
/// tables (USDA FoodData Central and IFCT for Indian staples). They are
/// planning estimates, not laboratory values.
abstract final class FoodDatabase {
  static const List<Food> all = <Food>[
    // ================= Protein anchors =================
    Food(
      id: 'eggs',
      name: 'Whole eggs',
      pattern: DietPattern.eggetarian,
      role: FoodRole.proteinAnchor,
      slots: <MealSlot>[MealSlot.breakfast, MealSlot.snack],
      servingLabel: '2 large eggs',
      kcal: 143,
      proteinG: 12.6,
      carbsG: 0.8,
      fatG: 9.5,
      benefits: <FoodBenefit>[
        FoodBenefit.protein,
        FoodBenefit.vitaminD,
        FoodBenefit.zinc,
        FoodBenefit.healthyFat,
      ],
      note:
          'The yolk carries the vitamin D, zinc and cholesterol that '
          'testosterone is synthesised from. Do not throw it away.',
    ),
    Food(
      id: 'paneer',
      name: 'Paneer',
      pattern: DietPattern.vegetarian,
      role: FoodRole.proteinAnchor,
      slots: <MealSlot>[MealSlot.lunch, MealSlot.dinner, MealSlot.breakfast],
      servingLabel: '100 g',
      kcal: 296,
      proteinG: 18,
      carbsG: 1.2,
      fatG: 25,
      benefits: <FoodBenefit>[FoodBenefit.protein, FoodBenefit.healthyFat],
    ),
    Food(
      id: 'tofu',
      name: 'Firm tofu',
      pattern: DietPattern.vegan,
      role: FoodRole.proteinAnchor,
      slots: <MealSlot>[MealSlot.breakfast, MealSlot.lunch, MealSlot.dinner],
      servingLabel: '150 g',
      kcal: 218,
      proteinG: 24,
      carbsG: 5,
      fatG: 12,
      benefits: <FoodBenefit>[
        FoodBenefit.protein,
        FoodBenefit.magnesium,
        FoodBenefit.zinc,
      ],
    ),
    Food(
      id: 'soya_chunks',
      name: 'Soya chunks',
      pattern: DietPattern.vegan,
      role: FoodRole.proteinAnchor,
      slots: <MealSlot>[MealSlot.lunch, MealSlot.dinner],
      servingLabel: '50 g dry',
      kcal: 175,
      proteinG: 26,
      carbsG: 13,
      fatG: 0.5,
      benefits: <FoodBenefit>[FoodBenefit.protein, FoodBenefit.fibre],
    ),
    Food(
      id: 'lentils',
      name: 'Lentils / dal',
      pattern: DietPattern.vegan,
      role: FoodRole.proteinAnchor,
      slots: <MealSlot>[MealSlot.lunch, MealSlot.dinner],
      servingLabel: '1 cup cooked (200 g)',
      kcal: 230,
      proteinG: 18,
      carbsG: 40,
      fatG: 0.8,
      benefits: <FoodBenefit>[
        FoodBenefit.protein,
        FoodBenefit.fibre,
        FoodBenefit.lowGi,
        FoodBenefit.magnesium,
      ],
    ),
    Food(
      id: 'chickpeas',
      name: 'Chickpeas',
      pattern: DietPattern.vegan,
      role: FoodRole.proteinAnchor,
      slots: <MealSlot>[MealSlot.lunch, MealSlot.dinner],
      servingLabel: '1 cup cooked (165 g)',
      kcal: 269,
      proteinG: 14.5,
      carbsG: 45,
      fatG: 4.2,
      benefits: <FoodBenefit>[
        FoodBenefit.protein,
        FoodBenefit.fibre,
        FoodBenefit.lowGi,
        FoodBenefit.zinc,
      ],
    ),
    Food(
      id: 'greek_yogurt',
      name: 'Greek yogurt',
      pattern: DietPattern.vegetarian,
      role: FoodRole.proteinAnchor,
      slots: <MealSlot>[MealSlot.breakfast, MealSlot.snack],
      servingLabel: '170 g pot',
      kcal: 100,
      proteinG: 17,
      carbsG: 6,
      fatG: 0.7,
      benefits: <FoodBenefit>[FoodBenefit.protein],
    ),
    Food(
      id: 'cottage_cheese',
      name: 'Cottage cheese',
      pattern: DietPattern.vegetarian,
      role: FoodRole.proteinAnchor,
      slots: <MealSlot>[MealSlot.breakfast, MealSlot.snack, MealSlot.dinner],
      servingLabel: '150 g',
      kcal: 120,
      proteinG: 17,
      carbsG: 5,
      fatG: 2.5,
      benefits: <FoodBenefit>[FoodBenefit.protein],
    ),
    Food(
      id: 'chicken_breast',
      name: 'Chicken breast',
      pattern: DietPattern.nonVegetarian,
      role: FoodRole.proteinAnchor,
      slots: <MealSlot>[MealSlot.lunch, MealSlot.dinner],
      servingLabel: '150 g cooked',
      kcal: 248,
      proteinG: 46,
      carbsG: 0,
      fatG: 5.4,
      benefits: <FoodBenefit>[FoodBenefit.protein, FoodBenefit.zinc],
    ),
    Food(
      id: 'salmon',
      name: 'Salmon',
      pattern: DietPattern.nonVegetarian,
      role: FoodRole.proteinAnchor,
      slots: <MealSlot>[MealSlot.lunch, MealSlot.dinner],
      servingLabel: '120 g',
      kcal: 240,
      proteinG: 25,
      carbsG: 0,
      fatG: 15,
      benefits: <FoodBenefit>[
        FoodBenefit.protein,
        FoodBenefit.omega3,
        FoodBenefit.vitaminD,
        FoodBenefit.healthyFat,
      ],
      note:
          'Omega-3 improves the flexibility of blood vessel walls, which is '
          'exactly the tissue an erection depends on.',
    ),
    Food(
      id: 'white_fish',
      name: 'White fish (cod, tilapia)',
      pattern: DietPattern.nonVegetarian,
      role: FoodRole.proteinAnchor,
      slots: <MealSlot>[MealSlot.lunch, MealSlot.dinner],
      servingLabel: '150 g',
      kcal: 130,
      proteinG: 28,
      carbsG: 0,
      fatG: 1.5,
      benefits: <FoodBenefit>[FoodBenefit.protein],
    ),
    Food(
      id: 'sardines',
      name: 'Sardines',
      pattern: DietPattern.nonVegetarian,
      role: FoodRole.proteinAnchor,
      slots: <MealSlot>[MealSlot.lunch, MealSlot.snack],
      servingLabel: '100 g tin',
      kcal: 208,
      proteinG: 25,
      carbsG: 0,
      fatG: 11,
      benefits: <FoodBenefit>[
        FoodBenefit.protein,
        FoodBenefit.omega3,
        FoodBenefit.vitaminD,
      ],
    ),
    Food(
      id: 'oysters',
      name: 'Oysters',
      pattern: DietPattern.nonVegetarian,
      role: FoodRole.proteinAnchor,
      slots: <MealSlot>[MealSlot.dinner],
      servingLabel: '6 medium',
      kcal: 70,
      proteinG: 8,
      carbsG: 4,
      fatG: 2,
      benefits: <FoodBenefit>[FoodBenefit.zinc, FoodBenefit.protein],
      note:
          'The densest dietary source of zinc there is. Zinc is a cofactor '
          'in testosterone synthesis - which is where the folklore came from.',
    ),

    // ================= Complex carbohydrates =================
    Food(
      id: 'oats',
      name: 'Rolled oats',
      pattern: DietPattern.vegan,
      role: FoodRole.complexCarb,
      slots: <MealSlot>[MealSlot.breakfast],
      servingLabel: '50 g dry',
      kcal: 190,
      proteinG: 6.5,
      carbsG: 33,
      fatG: 3.4,
      benefits: <FoodBenefit>[
        FoodBenefit.fibre,
        FoodBenefit.lowGi,
        FoodBenefit.magnesium,
      ],
    ),
    Food(
      id: 'brown_rice',
      name: 'Brown rice',
      pattern: DietPattern.vegan,
      role: FoodRole.complexCarb,
      slots: <MealSlot>[MealSlot.lunch, MealSlot.dinner],
      servingLabel: '1 cup cooked (195 g)',
      kcal: 218,
      proteinG: 4.5,
      carbsG: 46,
      fatG: 1.6,
      benefits: <FoodBenefit>[FoodBenefit.fibre, FoodBenefit.magnesium],
    ),
    Food(
      id: 'roti',
      name: 'Whole wheat roti',
      pattern: DietPattern.vegan,
      role: FoodRole.complexCarb,
      slots: <MealSlot>[MealSlot.lunch, MealSlot.dinner],
      servingLabel: '2 medium',
      kcal: 200,
      proteinG: 6,
      carbsG: 40,
      fatG: 3,
      benefits: <FoodBenefit>[FoodBenefit.fibre],
    ),
    Food(
      id: 'quinoa',
      name: 'Quinoa',
      pattern: DietPattern.vegan,
      role: FoodRole.complexCarb,
      slots: <MealSlot>[MealSlot.lunch, MealSlot.dinner],
      servingLabel: '1 cup cooked (185 g)',
      kcal: 222,
      proteinG: 8,
      carbsG: 39,
      fatG: 3.6,
      benefits: <FoodBenefit>[
        FoodBenefit.fibre,
        FoodBenefit.lowGi,
        FoodBenefit.magnesium,
        FoodBenefit.protein,
      ],
    ),
    Food(
      id: 'sweet_potato',
      name: 'Sweet potato',
      pattern: DietPattern.vegan,
      role: FoodRole.complexCarb,
      slots: <MealSlot>[MealSlot.lunch, MealSlot.dinner],
      servingLabel: '150 g baked',
      kcal: 135,
      proteinG: 2.4,
      carbsG: 31,
      fatG: 0.2,
      benefits: <FoodBenefit>[FoodBenefit.fibre, FoodBenefit.lowGi],
    ),

    // ================= Vegetables (blood flow) =================
    Food(
      id: 'beetroot',
      name: 'Beetroot',
      pattern: DietPattern.vegan,
      role: FoodRole.vegetable,
      slots: <MealSlot>[MealSlot.lunch, MealSlot.dinner, MealSlot.snack],
      servingLabel: '1 cup cooked (170 g)',
      kcal: 75,
      proteinG: 2.9,
      carbsG: 17,
      fatG: 0.3,
      benefits: <FoodBenefit>[FoodBenefit.nitrate, FoodBenefit.fibre],
      note:
          'Dietary nitrate converts to nitric oxide, the signalling molecule '
          'that relaxes penile arteries. This is the same pathway ED '
          'medication acts on, at a far smaller magnitude.',
    ),
    Food(
      id: 'spinach',
      name: 'Spinach',
      pattern: DietPattern.vegan,
      role: FoodRole.vegetable,
      slots: <MealSlot>[MealSlot.breakfast, MealSlot.lunch, MealSlot.dinner],
      servingLabel: '1 cup cooked (180 g)',
      kcal: 41,
      proteinG: 5.3,
      carbsG: 6.8,
      fatG: 0.5,
      benefits: <FoodBenefit>[
        FoodBenefit.nitrate,
        FoodBenefit.magnesium,
        FoodBenefit.fibre,
      ],
    ),
    Food(
      id: 'broccoli',
      name: 'Broccoli',
      pattern: DietPattern.vegan,
      role: FoodRole.vegetable,
      slots: <MealSlot>[MealSlot.lunch, MealSlot.dinner],
      servingLabel: '150 g',
      kcal: 51,
      proteinG: 4.2,
      carbsG: 10,
      fatG: 0.6,
      benefits: <FoodBenefit>[FoodBenefit.fibre],
    ),
    Food(
      id: 'mixed_salad',
      name: 'Mixed leaf salad',
      pattern: DietPattern.vegan,
      role: FoodRole.vegetable,
      slots: <MealSlot>[MealSlot.lunch, MealSlot.dinner],
      servingLabel: '100 g',
      kcal: 25,
      proteinG: 1.5,
      carbsG: 4,
      fatG: 0.3,
      benefits: <FoodBenefit>[FoodBenefit.nitrate, FoodBenefit.fibre],
    ),
    Food(
      id: 'mushrooms',
      name: 'UV-exposed mushrooms',
      pattern: DietPattern.vegan,
      role: FoodRole.vegetable,
      slots: <MealSlot>[MealSlot.breakfast, MealSlot.dinner],
      servingLabel: '100 g',
      kcal: 22,
      proteinG: 3.1,
      carbsG: 3.3,
      fatG: 0.3,
      benefits: <FoodBenefit>[FoodBenefit.vitaminD],
      note:
          'One of very few plant sources of vitamin D, and the only one '
          'most vegans will eat regularly.',
    ),

    // ================= Fruit =================
    Food(
      id: 'watermelon',
      name: 'Watermelon',
      pattern: DietPattern.vegan,
      role: FoodRole.fruit,
      slots: <MealSlot>[MealSlot.snack, MealSlot.breakfast],
      servingLabel: '2 cups (300 g)',
      kcal: 90,
      proteinG: 1.8,
      carbsG: 22.6,
      fatG: 0.5,
      benefits: <FoodBenefit>[FoodBenefit.citrulline],
      note:
          'Contains citrulline, which the body converts to arginine and '
          'then to nitric oxide.',
    ),
    Food(
      id: 'pomegranate',
      name: 'Pomegranate',
      pattern: DietPattern.vegan,
      role: FoodRole.fruit,
      slots: <MealSlot>[MealSlot.snack, MealSlot.breakfast],
      servingLabel: '1 cup arils (174 g)',
      kcal: 144,
      proteinG: 2.9,
      carbsG: 32.5,
      fatG: 2,
      benefits: <FoodBenefit>[FoodBenefit.flavonoid, FoodBenefit.fibre],
    ),
    Food(
      id: 'berries',
      name: 'Mixed berries',
      pattern: DietPattern.vegan,
      role: FoodRole.fruit,
      slots: <MealSlot>[MealSlot.breakfast, MealSlot.snack],
      servingLabel: '150 g',
      kcal: 72,
      proteinG: 1,
      carbsG: 17,
      fatG: 0.5,
      benefits: <FoodBenefit>[
        FoodBenefit.flavonoid,
        FoodBenefit.fibre,
        FoodBenefit.lowGi,
      ],
      note:
          'Flavonoid intake tracks with lower rates of erectile difficulty '
          'in long-running cohort studies.',
    ),
    Food(
      id: 'banana',
      name: 'Banana',
      pattern: DietPattern.vegan,
      role: FoodRole.fruit,
      slots: <MealSlot>[MealSlot.breakfast, MealSlot.snack],
      servingLabel: '1 medium',
      kcal: 105,
      proteinG: 1.3,
      carbsG: 27,
      fatG: 0.4,
      benefits: <FoodBenefit>[FoodBenefit.magnesium],
    ),
    Food(
      id: 'apple',
      name: 'Apple',
      pattern: DietPattern.vegan,
      role: FoodRole.fruit,
      slots: <MealSlot>[MealSlot.snack],
      servingLabel: '1 medium',
      kcal: 95,
      proteinG: 0.5,
      carbsG: 25,
      fatG: 0.3,
      benefits: <FoodBenefit>[FoodBenefit.fibre, FoodBenefit.flavonoid],
    ),

    // ================= Healthy fats =================
    Food(
      id: 'almonds',
      name: 'Almonds',
      pattern: DietPattern.vegan,
      role: FoodRole.healthyFat,
      slots: <MealSlot>[MealSlot.snack, MealSlot.breakfast],
      servingLabel: '28 g (about 23)',
      kcal: 164,
      proteinG: 6,
      carbsG: 6,
      fatG: 14,
      benefits: <FoodBenefit>[
        FoodBenefit.healthyFat,
        FoodBenefit.magnesium,
        FoodBenefit.zinc,
      ],
    ),
    Food(
      id: 'walnuts',
      name: 'Walnuts',
      pattern: DietPattern.vegan,
      role: FoodRole.healthyFat,
      slots: <MealSlot>[MealSlot.snack, MealSlot.breakfast],
      servingLabel: '28 g',
      kcal: 185,
      proteinG: 4.3,
      carbsG: 3.9,
      fatG: 18.5,
      benefits: <FoodBenefit>[
        FoodBenefit.omega3,
        FoodBenefit.healthyFat,
        FoodBenefit.magnesium,
      ],
    ),
    Food(
      id: 'pumpkin_seeds',
      name: 'Pumpkin seeds',
      pattern: DietPattern.vegan,
      role: FoodRole.healthyFat,
      slots: <MealSlot>[MealSlot.snack, MealSlot.breakfast],
      servingLabel: '28 g',
      kcal: 151,
      proteinG: 7,
      carbsG: 5,
      fatG: 13,
      benefits: <FoodBenefit>[
        FoodBenefit.zinc,
        FoodBenefit.magnesium,
        FoodBenefit.healthyFat,
      ],
      note:
          'One of the best plant sources of both zinc and magnesium in a '
          'single food.',
    ),
    Food(
      id: 'flaxseed',
      name: 'Ground flaxseed',
      pattern: DietPattern.vegan,
      role: FoodRole.healthyFat,
      slots: <MealSlot>[MealSlot.breakfast, MealSlot.snack],
      servingLabel: '1 tbsp (10 g)',
      kcal: 55,
      proteinG: 1.9,
      carbsG: 3,
      fatG: 4.3,
      benefits: <FoodBenefit>[
        FoodBenefit.omega3,
        FoodBenefit.fibre,
        FoodBenefit.magnesium,
      ],
      note: 'Must be ground - whole flaxseed passes through undigested.',
    ),
    Food(
      id: 'olive_oil',
      name: 'Extra virgin olive oil',
      pattern: DietPattern.vegan,
      role: FoodRole.healthyFat,
      slots: <MealSlot>[MealSlot.lunch, MealSlot.dinner],
      servingLabel: '1 tbsp',
      kcal: 119,
      proteinG: 0,
      carbsG: 0,
      fatG: 13.5,
      benefits: <FoodBenefit>[FoodBenefit.healthyFat, FoodBenefit.flavonoid],
    ),
    Food(
      id: 'avocado',
      name: 'Avocado',
      pattern: DietPattern.vegan,
      role: FoodRole.healthyFat,
      slots: <MealSlot>[MealSlot.breakfast, MealSlot.lunch],
      servingLabel: 'half a medium fruit',
      kcal: 160,
      proteinG: 2,
      carbsG: 8.5,
      fatG: 14.7,
      benefits: <FoodBenefit>[
        FoodBenefit.healthyFat,
        FoodBenefit.fibre,
        FoodBenefit.magnesium,
      ],
    ),
    Food(
      id: 'peanut_butter',
      name: 'Peanut butter',
      pattern: DietPattern.vegan,
      role: FoodRole.healthyFat,
      slots: <MealSlot>[MealSlot.breakfast, MealSlot.snack],
      servingLabel: '2 tbsp (32 g)',
      kcal: 190,
      proteinG: 7,
      carbsG: 7,
      fatG: 16,
      benefits: <FoodBenefit>[FoodBenefit.healthyFat, FoodBenefit.magnesium],
    ),
    Food(
      id: 'dark_chocolate',
      name: 'Dark chocolate (85%)',
      pattern: DietPattern.vegetarian,
      role: FoodRole.healthyFat,
      slots: <MealSlot>[MealSlot.snack],
      servingLabel: '20 g',
      kcal: 120,
      proteinG: 2,
      carbsG: 6,
      fatG: 10,
      benefits: <FoodBenefit>[
        FoodBenefit.flavonoid,
        FoodBenefit.magnesium,
        FoodBenefit.healthyFat,
      ],
    ),

    // ================= Beverages / fortified =================
    Food(
      id: 'milk',
      name: 'Fortified milk',
      pattern: DietPattern.vegetarian,
      role: FoodRole.beverage,
      slots: <MealSlot>[MealSlot.breakfast, MealSlot.snack],
      servingLabel: '250 ml',
      kcal: 122,
      proteinG: 8,
      carbsG: 12,
      fatG: 4.8,
      benefits: <FoodBenefit>[FoodBenefit.protein, FoodBenefit.vitaminD],
    ),
    Food(
      id: 'soy_milk',
      name: 'Fortified soy milk',
      pattern: DietPattern.vegan,
      role: FoodRole.beverage,
      slots: <MealSlot>[MealSlot.breakfast, MealSlot.snack],
      servingLabel: '250 ml',
      kcal: 100,
      proteinG: 7,
      carbsG: 8,
      fatG: 4,
      benefits: <FoodBenefit>[FoodBenefit.protein, FoodBenefit.vitaminD],
    ),
  ];

  static Food byId(String id) => all.firstWhere((Food f) => f.id == id);

  static List<Food> forPattern(DietPattern pattern) =>
      all.where(pattern.canEat).toList();

  static List<Food> withBenefit(FoodBenefit benefit) =>
      all.where((Food f) => f.hasBenefit(benefit)).toList();
}
