import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform;

/// Firebase configuration, supplied at build time rather than checked in.
///
/// Normally this file is generated by `flutterfire configure`, which writes
/// the project's identifiers straight into source. We read them from
/// `--dart-define` instead so that a fork or a CI build can point at its own
/// Firebase project without editing code, and so nothing project-specific
/// lands in the repository.
///
/// These values are not secrets - they identify the project and are
/// extractable from any shipped binary - but keeping them out of source
/// keeps the repo portable.
///
/// To generate real values:
/// ```
/// dart pub global activate flutterfire_cli
/// flutterfire configure --project=<your-project>
/// ```
/// then copy the identifiers into your `env/*.json` define file.
class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform => switch (defaultTargetPlatform) {
    TargetPlatform.android => android,
    TargetPlatform.iOS => ios,
    _ => throw UnsupportedError(
      'VitalRise ships on Android and iOS only. Firebase options for '
      '$defaultTargetPlatform have not been configured.',
    ),
  };

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
    appId: String.fromEnvironment('FIREBASE_ANDROID_APP_ID'),
    messagingSenderId: String.fromEnvironment('FIREBASE_SENDER_ID'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET'),
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY'),
    appId: String.fromEnvironment('FIREBASE_IOS_APP_ID'),
    messagingSenderId: String.fromEnvironment('FIREBASE_SENDER_ID'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET'),
    iosBundleId: String.fromEnvironment(
      'IOS_BUNDLE_ID',
      defaultValue: 'io.vitalrise.app',
    ),
  );
}
